# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-06 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_logo',
            field=models.IntegerField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='image',
            name='preidcted',
            field=models.IntegerField(),
        ),
    ]
