# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-06 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retina', '0003_auto_20170206_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='preidcted',
            field=models.IntegerField(null=True),
        ),
    ]
